spring:
  application:
    name: springboot-activiti-explorer
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  #html静态页面路径
  resources:
    static-locations: classpath:static/,file:static/
  #activiti
  #表示启动时检查数据库表，不存在则创建
  activiti:
    database-schema-update: true
    #表示哪种情况下使用历史表，这里配置为full表示全部记录历史，方便绘制流程图
    history-level: full
    #true表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表
    db-history-used: true
    #校验流程定义规范
    check-process-definitions: false
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity